#
- name: nginx - add repository key
  apt_key:
    url: "http://nginx.org/keys/nginx_signing.key"

- name: nginx - add repository (apt)
  apt_repository:
    repo: "{{ item }}"
    update_cache: yes
  with_items:
    - "deb http://nginx.org/packages/mainline/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx"
    - "deb-src http://nginx.org/packages/mainline/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release }} nginx"

- name: nginx - install
  apt:
    name: "nginx"
    state: "latest"

- name: nginx - create virtuals directory
  file:
    path: "/etc/nginx/virtuals"
    state: "directory"
    mode: 0755
    owner: "root"
    group: "root"

- name: nginx - main configuration file
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    mode: 0644
    owner: "root"
    group: "root"
